### ISSUE TITLE
Barbarik with SPUR: issue

### ISSUE THREAD

**Issue by FAMILIAR-project** [FAMILIAR-project/usampling-exp#17]
This experiment `Namespace(delta=0.05, epsilon=0.3, eta=0.9, exp=1, formulas=['/home/samplingfm/Benchmarks/Blasted_Real/blasted_squaring26.cnf', '/home/samplingfm/Benchmarks/V15/s526_15_7.cnf'], maxSamples=9223372036854775807, minSamples=0, ref_sampler=6, sampler=9, searchOrder=0, seed=1, thres=5600, verbose=1)`
over two formulae, ref_sampler=6 (SPUR), sampler=KUS

```
b'Experiment: 0     of     1\nconstantFactor:39   boundFactor: 14.541336623567457   logBoundFactor: 3.8620879811712894  \ntj: 1789   totalLoops: 2     beta: 0.8181818181818182 epsilon: 0.3       \nnumSolutions: 568   loThresh:82     hiThresh: 485   \n*** Progress *** i: 0 j: 2 ---- 0 / 3578\nUsing sampler: KUS\ncmd:  python3  KUS.py --samples=1 --outputfile /tmp/blasted_squaring26.txt /home/samplingfm/Benchmarks/Blasted_Real/blasted_squaring26.cnf > /dev/null 2>&1\n'
--
```

`b'Traceback (most recent call last):\n  File "barbarik.py", line 1096, in <module>\n    ok, breakExperiment = exp.one_experiment(experiment, j, i, numExperiments, tj)\n  File "barbarik.py", line 963, in one_experiment\n    self.inputFile, 1, self.samplerType, self.indVarList, newSeed)\n  File "barbarik.py", line 196, in getSolutionFromSampler\n    sols = SolutionRetriver.getSolutionFromKUS(*topass_withseed)\n  File "barbarik.py", line 299, in getSolutionFromKUS\n    with open(tempOutputFile, \'r\') as f:\nFileNotFoundError: [Errno 2] No such file or directory: \'/tmp/blasted_squaring26.txt\'\n'`

and

```
b'Experiment: 0     of     1\nconstantFactor:39   boundFactor: 14.541336623567457   logBoundFactor: 3.8620879811712894  \ntj: 1789   totalLoops: 2     beta: 0.8181818181818182 epsilon: 0.3       \nnumSolutions: 568   loThresh:82     hiThresh: 485   \n*** Progress *** i: 0 j: 2 ---- 0 / 3578\nUsing sampler: KUS\ncmd:  python3  KUS.py --samples=1 --outputfile /tmp/s526_15_7.txt /home/samplingfm/Benchmarks/V15/s526_15_7.cnf > /dev/null 2>&1\nNumber of solutions returned by sampler: 10\nUsing sampler: SPUR\ncmd:  ./samplers/spur -seed 1791 -q -s 1 -out /tmp/s526_15_7.out -cnf /home/samplingfm/Benchmarks/V15/s526_15_7.cnf\n'
--
```

`b'sh: 1: ./samplers/spur: not found\nTraceback (most recent call last):\n  File "barbarik.py", line 1096, in <module>\n    ok, breakExperiment = exp.one_experiment(experiment, j, i, numExperiments, tj)\n  File "barbarik.py", line 974, in one_experiment\n    self.inputFile, 1, self.ref_sampler_type, self.indVarList, newSeed)\n  File "barbarik.py", line 187, in getSolutionFromSampler\n    sols = SolutionRetriver.getSolutionFromSpur(*topass_withseed)\n  File "barbarik.py", line 467, in getSolutionFromSpur\n    with open(tempOutputFile, \'r\') as f:\nFileNotFoundError: [Errno 2] No such file or directory: \'/tmp/s526_15_7.out\'\n'`

**Comment by gperroui** [comment]
I do not know in which environment it has been run but you need to make sure that pydot and pandas are installed (e.g. pip install pydot pandas) for KUS.py to run properly (first error). The second issue seems to miss spur in the sampler directory... Is there a problem with the docker image?

**Comment by FAMILIAR-project** [comment]
I recommend to use mount/volumes to develop:
`docker run -it -v $(pwd):/home/usampling-exp:z macher/usampling:squashed /bin/bash`

like this,  you can edit files that are bound/mounted to the Docker file. And experiments with procedures/samplers are inside the Docker. We will have the same environment (in the grid I'm using this Docker). 

note the tag (squashed) `macher/usampling:squashed`

Hence my question: do you obtain similar things with the Docker image?

**Comment by gperroui** [comment]
When I pulled the image, I obtained other errors (due to an old version of BarbarikLoop/Barbarik) related to some wrong paths in the predefined repositories. There is no problem if I mount the the git contents on my host to the docker image as explained above. I also managed to update my local image by copying the BarbarikLoop and Barbarik scripts from git and run everything within the container (without mounting folders). I hope it helps.

**Comment by acherm** [comment]
seems working on my machine as well: 
```
python3 barbarik.py --maxSamples 9223372036854775807 --minSamples 0 --ref-sampler 6 --sampler 9 --seed 1 --delta 0.05 --epsilon 0.3 --eta 0.9 /home/samplingfm/Benchmarks/V15/s526_15_7.cnf
Experiment: 0     of     1
constantFactor:39   boundFactor: 14.541336623567457   logBoundFactor: 3.8620879811712894  
tj: 1789   totalLoops: 2     beta: 0.8181818181818182 epsilon: 0.3       
numSolutions: 568   loThresh:82     hiThresh: 485   
Using sampler: KUS
Number of solutions returned by sampler: 1
Using sampler: SPUR
Number of solutions returned by sampler: 1
Using sampler: KUS
Number of solutions returned by sampler: 568
baseMap: 568    numSolutions: 568    SolutionsCount: 300    loThresh: 82     hiThresh: 485   
sampler: KUS      i: 1    isUniform: 1    TotalSolutionsGenerated: 569   
Using sampler: KUS
Number of solutions returned by sampler: 1
Using sampler: SPUR
Number of solutions returned by sampler: 1
Using sampler: KUS
Number of solutions returned by sampler: 568
baseMap: 568    numSolutions: 568    SolutionsCount: 568    loThresh: 82     hiThresh: 485   
sampler: KUS      i: 2    isUniform: 0    TotalSolutionsGenerated: 1138  
exp:0 RejectIteration:2  Loop:2 TotalSolutionsGenerated:1138 TotalUniformSamples:2
```

strange, I will investigate on the grid

**Comment by acherm** [comment]
seems OK now, see also #14 
but we have another problem
