### ISSUE TITLE
STS sampler: too large population? 

### ISSUE THREAD

**Issue by FAMILIAR-project** [FAMILIAR-project/usampling-exp#3]
```
root@f7e546a491c6:/home/usampling-exp# python3 barbarik.py --sampler 3 --seed 42 ../samplingfm/Benchmarks/FeatureModels/FM-3.6.1-refined.cnf
Experiment: 0     of     1
constantFactor:39   boundFactor: 14.541336623567457   logBoundFactor: 3.8620879811712894  
tj: 1789   totalLoops: 2     beta: 0.8181818181818182 epsilon: 0.3       
numSolutions: 568   loThresh:82     hiThresh: 485   
Using sampler: STS
Number of solutions returned by sampler: 1
Using sampler: SPUR
Number of solutions returned by sampler: 1
Traceback (most recent call last):
  File "barbarik.py", line 961, in <module>
    ok, breakExperiment = exp.one_experiment(experiment, j, i, numExperiments, tj)
  File "barbarik.py", line 852, in one_experiment
    chainFormulaConf = chainFormulaSetup(sampleSol, unifSol, self.numSolutions)
  File "barbarik.py", line 579, in chainFormulaSetup
    sampleLitList = random.sample(sampleSol.split(), len(countList))
  File "/usr/local/lib/python3.7/random.py", line 321, in sample
    raise ValueError("Sample larger than population or is negative")
ValueError: Sample larger than population or is negative

```

**Comment by gperroui** [comment]
The root cause of the problem comes from STS that is not able to produce samples for a number of models (including all feature models in the feature models repository). Hence, there is nothing to sample.  To make it clear an assertion has been added in Barbarik script and the standard error is now collected in the uniformity result CSV: https://github.com/FAMILIAR-project/usampling-exp/commit/9c9e76bb86e7c24a1bac97f3ff454044418a919f
